### ISSUE TITLE
allow piping of csv/xml

### ISSUE THREAD

**Issue by cz8s** [zuntrax/schedule-ng#27]
It would be awesome if  schedule.py could read the csv from stdin and write the xml to stdout.
One could pipe like this
 `wget URL | ./voctosched.py | tee STH`

It would be very nice feature when using docker

**Comment by zuntrax** [comment]
Please note that `wget | ./schedule` is mostly obsolete because voctosched can download input files via HTTP. I still added it for other use cases.
