### ISSUE TITLE
Importing from csv leads to broken XML

### ISSUE THREAD

**Issue by dvzrv** [zuntrax/schedule-ng#34]
I'm currently exporting the data for Linux Audio Conference 2018, using voctosched to build a fahrplan.xml from a DIY csv ([with the demo csv as guidance](https://github.com/voc/voctosched/blob/master/demo/gpn11.csv)). This seems to work without issues (now), but the generated XML doesn't lint using the [xsd validator](https://github.com/voc/schedule/tree/34C3/validator/xsd).
Running the script as explained in the README, leads to:

```
../lac2018/files/lac2018.xml:34: element links: Schemas validity error : Element 'links': Character content other than whitespace is not allowed because the content type 
is 'element-only'.
```

And sure enough, in the XML I'll find

```
<links>None</links>
<attachments>None</attachments>
```

per event!

Is the import_handler for csv broken and inserts `None` to those nodes or am I missing something import?

**Comment by zuntrax** [comment]
Seems like I broke this, working on a fix.
